### ISSUE TITLE
Format parsed and returned as [object Object]

### ISSUE THREAD

**Issue by jonkristian** [rroppolo/bootstrap-multisuggestplugin#2]
Not sure if it's related to your plugin or maybe a mistake on my end but with this format it doesn't appear to work:

[{"id":"1","title":"Post Title"}]

My js:

``` javascript
        $('input[name="posts"]').multisuggest({
            sources: [
                {
                    type: 'url',
                    data: '/public/admin/posts/getposts',
                    queryParam: 'query',
                    header: 'Posts',
                    maxEntries: 5
                }
            ],
            link: '<a tabFocus="0" href="#">Invite a new user</a>',
            linkHandler: function() {
                // show invitation form
            },
            loadingIconClass: "usuggest-loading",
            noResultsText: "No posts.",
            enableDropdownMode: true,
            delay: 300,
            minLength: 2
        });
```

I suspect it's because of the double quotes in my response?

**Comment by jabbett** [comment]
By default, the plugin doesn't know what kind of data to expect from your web service, so when you define a `url` source, you need to include the `listFormatter`, `inputFormatter`, `valueAttribute`, and `resultsProcessor` methods.

See the "AJAX results" example in [the live demo](http://htmlpreview.github.io/?https://github.com/rroppolo/bootstrap-multisuggestplugin/blob/master/demo.html).

**Comment by jonkristian** [comment]
Ah, thanks got it:)
On a sidenote: It might be good if you gave an example without the 3rd party templating, I think it will make more sense to people:)
